# Generated by Django 5.0.6 on 2024-06-09 18:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('colour', colorfield.fields.ColorField(default='#EEEEEE', image_field=None, max_length=25, samples=None)),
                ('contrast_colour', colorfield.fields.ColorField(default='#4E4E4E', image_field=None, max_length=25, samples=None)),
                ('use_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.tag'),
        ),
    ]
